### ISSUE TITLE
Double zip a folder?

### ISSUE THREAD

**Issue by cinder92** [alanhoff/node-tar.gz#11] opened 2014-06-21 18:18 UTC
Hello i have an issue, i want to zip a folder with few images, i have this code

 var baseDatos = new targz(6,6,true).compress(app.execPath.replace(/\\/g, '/') + "dbfiles/", app.resourcesDir + "/" + db, function(err){
                if(err)
                     console.log('err')
                location.href = app.resourcesDir + "/"+ db;
            });

when i open the zip file, as the same time it has another file without extention, but if i put ".zip" like extention, and i open this one zip, it contains all my files but, why is duble ziping?

![captura de pantalla 2014-06-21 a la s 13 20 01](https://cloud.githubusercontent.com/assets/4725556/3349633/72e6a1ce-f970-11e3-8647-ea73e187cc4d.png)

**Comment by alanhoff** [comment] 2015-08-09 23:04
I will close this issue because of the code rewrite, fell free to reopen if the problem is still there.

**Closed by alanhoff** 2015-08-09 23:04 UTC
