### ISSUE TITLE
[Error: incorrect header check] errno: -3, code: 'Z_DATA_ERROR'

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [alanhoff/node-tar.gz#13] opened 2015-01-18 16:25 UTC
Hi, 

I am getting this error. However this is not why I am opening this issue. 

The problem is that there's no way to catch this error as it is something that happens inside nextTick, and the library does not catch it. 

So technically there are 2 problems: 
 - The error itself
 - The library does not propagate the error properly. 

If it helps, this is all the stacktrace I am getting.. 
```
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)
```

**Comment by czy88840616** [comment] 2015-03-27 02:26
I have the same problem。。。I can't catch the error...

**Comment by guy-mograbi-at-gigaspaces** [comment] 2015-03-29 14:01
we resolved this by implementing our own.. 
it seems this library is pretty small and it is very easy to simply copy paste its code and fix it. it also allowed us to easily add support both for tar and tar.gz - as a fallback.

**Comment by ssimono** [comment] 2015-06-19 16:26
Correct me if I'm wrong, but the PR #6 merged on **19 Oct 2013** on master is supposed to fix this and propagate the error.

Unfortunately the npm module has not been update on the registry. The last 4 commits have never been published

@cranic could you just update package version to **0.1.2** and `npm publish` ?

Thx

**Comment by alanhoff** [comment] 2015-08-09 23:03
I will close this issue because of the code rewrite, fell free to reopen if the problem is still there.

**Closed by alanhoff** 2015-08-09 23:03 UTC
