### ISSUE TITLE
Didn't get expected byte count expect: 851968 actual: 1834789

### ISSUE THREAD

**Issue by sanket-mindstix** [alanhoff/node-tar.gz#12] opened 2014-11-24 10:15 UTC
I am getting above error on performing follwing function call 
new targz().compress()
Following is stack trace
 at decorate (~/node_modules/tar.gz/node_modules/fstream/lib/abstract.js:67:36)
    at FileReader.Abstract.error (~/node_modules/tar.gz/node_modules/fstream/lib/abstract.js:61:12)
    at ReadStream.<anonymous> (~/node_modules/tar.gz/node_modules/fstream/lib/file-reader.js:66:10)
    at ReadStream.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

**Comment by alanhoff** [comment] 2015-08-09 23:03
I will close this issue because of the code rewrite, fell free to reopen if the problem is still there.

**Closed by alanhoff** 2015-08-09 23:03 UTC

**Comment by SudharsanN** [comment] 2017-03-09 01:17
We are  encountering the same issue when we are using targz().compress(). Below is the stack trace.

Error: Didn't get expected byte count expect: 1703936 actual: 12112951   at decorate (C:\\Sudharsan\\Workspace\\release-v1.11\\ce-billing\\DowJones.CustomerEngine.Billing\\DowJones.CustomerEngine.Billing.Ddp.Edw\\node_modules\\fstream\\lib\\abstract.js:67:36)\n    at FileReader.Abstract.error (C:\\Sudharsan\\Workspace\\release-v1.11\\ce-billing\\DowJones.CustomerEngine.Billing\\DowJones.CustomerEngine.Billing.Ddp.Edw\\node_modules\\fstream\\lib\\abstract.js:61:12)\n    at ReadStream.<anonymous> (C:\\Sudharsan\\Workspace\\release-v1.11\\ce-billing\\DowJones.CustomerEngine.Billing\\DowJones.CustomerEngine.Billing.Ddp.Edw\\node_modules\\fstream\\lib\\file-reader.js:65:12)\n    at emitNone (events.js:91:20)\n    at ReadStream.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","time":"2017-03-08T20:19:21.188Z","v":0}

We are using version 1.0.5 of tar.gz. Can you let us know how to fix this?
