### ISSUE TITLE
callback seems not work, i must use settimeout() .

### ISSUE THREAD

**Issue by foxtail000** [alanhoff/node-tar.gz#20] opened 2015-10-11 11:33 UTC
targz().extract('/bkp/backup.tar.gz', '/home/myuser', function(err){
  if(err){
    console.log('Something is wrong ', err.stack);
    callback err.stack
}
  console.log('Job done!');
  callback();
});

**Comment by sahil87** [comment] 2015-11-05 12:04
Facing the same issue. Call back gets called after the first file is extracted. (vs. after the whole archive is extracted). Had to use setTimeout to solve this.

**Comment by mlarcher** [comment] 2015-11-23 12:46
Had the same issue, I eventually switched to the 'decompress' module since there was no response to this issue after a month.

**Comment by HiveSolution** [comment] 2015-12-02 16:17
Having the same issue. setTimeout as a workaround kinda works, but I will have to look for another package until this is fixed.

**Comment by alanhoff** [comment] 2015-12-28 19:13
Hello folks, sorry for the delay. It seems like `fstream` is not triggering the event I wanted, I'll take a look as soon as I can

**Comment by HiveSolution** [comment] 2015-12-28 20:53
Thanks for taking a look at this. Once it's fixed I will jump back to your package.

**Comment by BenasPaulikas** [comment] 2016-01-13 14:43
Having same issue. setTimeout is temporary solution. I'm just curious, so please correct me if I'm wrong - problem is that all input stream is finished(in this stage we get our callback executed) but output is not yet done?

**Comment by fjmilens3** [comment] 2016-02-02 00:11
One place to look might be that the underlying write stream that handles the finish event (https://github.com/alanhoff/node-tar.gz/blob/master/index.js#L158) is created in another method (https://github.com/alanhoff/node-tar.gz/blob/master/index.js#L154), and in that method, the write stream that is returned is actually the initial write stream that decompresses the archive, not the write stream that extracts the decompressed contents (https://github.com/alanhoff/node-tar.gz/blob/master/index.js#L62).

I'm wondering if this issue isn't caused by a brief 'blip' between the time the first stream has completed and the second one has completed, which would explain why `setTimeout` seems to help by providing a buffer (and some other bug reports that indicate the archive sometimes appears to be partially-extracted when the callback is fired).

The fix is a bit more complicated and would likely be best done by @alanhoff or someone else familiar with the underlying intention of the codebase, mostly because you still need the initial stream to be able to pipe the content from the archive into it. It's just that you probably only want to consider things 'done' once the second stream has fired a finish event, but it seems like we're actually getting the first one.

If this is the cause, the fix is somewhat straightforward, but it would likely involve more refashioning of how the combined write stream is created and returned so that you can feed the content from the file into the first stream but listen for the finish event on the second, certainly not a one-line fix. That said, I feel somewhat confident as I was originally using this library on a project, and ended up having to use a very similar approach to what I've described here as a workaround to using this library in my own code.

**Comment by alanhoff** [comment] 2016-02-02 02:03
@fjmilens3 can you write a PR for this? I really don't care about code refactoring if this issue gets fixed.

**Comment by alanhoff** [comment] 2016-02-03 03:28
fixed by #28

**Closed by alanhoff** 2016-02-03 03:28 UTC
Labels: bug

**Comment by BenasPaulikas** [comment] 2016-02-04 23:08
But how do we get callback to this code ? Tried everything - no end or finish event is emmited ?

var request = require('request');
var targz = require('tar.gz');

// Streams
var read = request.get('https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz');
var write = targz().createWriteStream('/some/directory');

read.pipe(write);
