### ISSUE TITLE
tar.Pack messing with the root folder attributes

### ISSUE THREAD

**Issue by cranic** [alanhoff/node-tar.gz#10] opened 2014-03-20 16:17 UTC
[This is the only problem][0] that I need to resolve before releasing the new version. If someone could help me...

[0]: https://github.com/isaacs/node-tar/issues/30

**Comment by alanhoff** [comment] 2015-08-09 23:05
I will close this issue because of the code rewrite, fell free to reopen if the problem is still there.

**Closed** 2015-08-09 23:05 UTC
