### ISSUE TITLE
Executable is unsigned

### ISSUE THREAD

**Issue by adam-lynch** [alanhoff/node-tar.gz#14] opened 2015-02-02 14:04 UTC
This may be a problem when distributing a [nwjs](https://github.com/nwjs/nw.js) app using [node-webkit-updater](https://github.com/edjafarov/node-webkit-updater) (since it uses node-tar.gz).

**Comment by alanhoff** [comment] 2015-08-09 23:03
I will close this issue because of the code rewrite, fell free to reopen if the problem is still there.

**Closed by alanhoff** 2015-08-09 23:03 UTC
